class CreateZoneReqs < ActiveRecord::Migration[5.0]
  def change
    create_table :zone_reqs do |t|
      t.string :computed_region_rcj3_ccgu
      t.string :computed_region_rffn_qbt6
      t.string :computed_region_swkg_bavi
      t.date :applicationdate
      t.string :applied_online
      t.string :board_of_appeals_special_permit
      t.string :continued_operation
      t.string :current_use
      t.date :decisiondate
      t.string :desc_of_relief_req
      t.string :description
      t.string :description_of_other_occupancies
      t.string :desirable_relief_nullifying
      t.string :desirable_relief_public_good
      t.string :exisiting_lot_area
      t.string :existing_distance_to_nearest_bldg
      t.string :existing_gross_floor_area_ratio
      t.string :existing_lot_area_dwelling_unit
      t.string :existing_no_of_dwelling_units
      t.string :existing_no_of_loading_areas
      t.string :existing_no_of_parking_spaces
      t.string :existing_setbacks_back
      t.string :existing_setbacks_front
      t.string :existing_setbacks_left_side
      t.string :existing_setbacks_right_side
      t.string :existing_size_of_building_height
      t.string :existing_size_of_building_length
      t.string :existing_size_of_building_width
      t.string :existing_size_of_lot_depth
      t.string :existing_size_of_lot_width
      t.string :existing_usablek_open_space_ratio
      t.string :land_topography_hardship
      t.string :literal_enforcement
      t.string :location
      t.string :location_address
      t.string :location_city
      t.string :location_state
      t.string :location_zip
      t.string :nuisance_or_hazard
      t.string :ordinance_distance_to_nearest_building
      t.string :ordinance_gross_floor_area_ratio
      t.string :ordinance_lot_area
      t.string :ordinance_lot_area_dwelling_unit
      t.string :ordinance_no_of_dwelling_units
      t.string :ordinance_no_of_loading_areas
      t.string :ordinance_no_of_parking_spaces
      t.string :ordinance_setbacks_front
      t.string :ordinance_setbacks_left_side
      t.string :ordinance_setbacks_rear
      t.string :ordinance_setbacks_right_side
      t.string :ordinance_size_of_building_height
      t.string :ordinance_size_of_building_length
      t.string :ordinance_size_of_building_width
      t.string :ordinance_size_of_lot_depth
      t.string :ordinance_size_of_lot_width
      t.string :ordinance_total_gross_flr_area
      t.string :ordinance_useable_open_space_ratio
      t.string :other_reasons
      t.string :petitioner_city
      t.string :petitioner_state
      t.string :plan_number
      t.string :proposed_use
      t.string :reason_for_petition
      t.string :reason_for_petition_other
      t.string :requested_distance_to_nearest_bldg
      t.string :requested_gross_floor_area_ratio
      t.string :requested_lot_area
      t.string :requested_lot_area_dwelling_unit
      t.string :requested_no_of_dwelling_units
      t.string :requested_no_of_loading_areas
      t.string :requested_no_of_parking_spaces
      t.string :requested_setbacks_back
      t.string :requested_setbacks_front
      t.string :requested_setbacks_left_side
      t.string :requested_setbacks_right_side
      t.string :requested_size_of_building_height
      t.string :requested_size_of_building_length
      t.string :requested_size_of_building_width
      t.string :requested_size_of_lot_depth
      t.string :requested_size_of_lot_width
      t.string :requested_total_gross_flr_area
      t.string :requested_usable_open_space_ratio
      t.string :requirements_of_ordinance
      t.string :special_permit_decision_deadline
      t.string :special_permit_hearing_deadline
      t.string :status
      t.string :summary_for_publication
      t.string :total_gross_floor_area
      t.string :trafficpatterns
      t.string :type
      t.string :variance_board_of_appeals
      t.string :variance_decision_deadline
      t.string :variance_hearing_deadline
      t.string :zoning_district
      t.integer :zoning_ordinance_cited_article_field1
      t.integer :zoning_ordinance_cited_article_field2
      t.integer :zoning_ordinance_cited_article_field3
      t.integer :zoning_ordinance_cited_article_field4
      t.integer :zoning_ordinance_cited_article_field5
      t.integer :zoning_ordinance_cited_article_field6
      t.integer :zoning_ordinance_cited_article_field7
      t.string :zoning_ordinance_cited_section_field1
      t.string :zoning_ordinance_cited_section_field2
      t.string :zoning_ordinance_cited_section_field3
      t.string :zoning_ordinance_cited_section_field4
      t.string :zoning_ordinance_cited_section_field5
      t.string :zoning_ordinance_cited_section_field6
      t.string :zoning_ordinance_cited_section_field7
      t.string :zoning_use_classification
      
      t.timestamps
    end
  end
end
